In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.1'

In [3]:
df=pd.read_csv("car_fuel_efficiency.csv")
df.shape[0]

9704

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [8]:
df.fuel_type.nunique()

2

In [11]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [20]:
df [df['origin'] == 'Asia'].groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia    23.759123
Name: fuel_efficiency_mpg, dtype: float64

In [21]:
df['horsepower'].median()

np.float64(149.0)

In [22]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [24]:
df['horsepower'].fillna(df['horsepower'].mode()[0],inplace=True)

/tmp/ipykernel_11204/359411204.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].mode()[0],inplace=True)


In [25]:
df['horsepower'].median()

np.float64(152.0)

In [54]:
df=pd.read_csv("car_fuel_efficiency.csv")

In [55]:
df[df['origin'] == 'Asia' ][['vehicle_weight','model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [66]:
df_array =  df[df['origin'] == 'Asia' ][['vehicle_weight','model_year']].head(7)
X = df_array.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [76]:
XT=X.T
XTX = XT.dot(X)

XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [68]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [82]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
XI=np.linalg.inv(XTX)
w = XI.dot(XT).dot(y)
np.sum(w)

np.float64(0.5187709081074016)